# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: 
    'true'
  branches:
    include:
    - master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  outputFile: '$(Build.BuildId)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$Revision = git describe --first-parent --always;
    Write-Host "##vso[task.setvariable variable=outputFile]$(Build.BuildId)-$Revision";
    Set-Content "./Program/Revision.txt" "`$Revision 1.3.1-$env:outputFile `$";'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './Program/'
    includeRootFolder: true 
    archiveFile: "$(Build.ArtifactStagingDirectory)/$(outputFile).zip"  
    verbose: true # Optional

- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(outputFile).zip'
    ConnectedServiceNameARM: 'Visual Studio Enterprise(81c98ddc-0e66-422e-af90-10337e5c2352)'
    Destination: 'AzureBlob'
    StorageAccountRM: 'ultimaterails'
    ContainerName: 'ci-builds'
    BlobPrefix: 'ci'
